{% set name = "mp-api" %}
{% set version = "0.37.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-api-{{ version }}.tar.gz
  sha256: 0f0734b382429ee4c53d2d333cf004f6db9c1b0395532b3702ec8158b11d093d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - boto3
    - emmet-core >=0.69.2
    - maggma
    - monty >=2021.3.12
    - msgpack-python
    - pymatgen >=2022.3.7
    - python >=3.8
    - requests >=2.23.0
    - setuptools
    - typing-extensions >=3.7.4.1

test:
  imports:
    - mp_api.client
    - mp_api.client.core
  commands:
    - pip check
    - pip show mp-api
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Server for the Materials Project
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
