{% set name = "mp-api" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-api-{{ version }}.tar.gz
  sha256: bce602f3847be1e196773c0c875950a80011efcd7ca70c4b0b14bb1a4bba9927

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - emmet-core >=0.36.4
    - monty >=2021.3.12
    - msgpack-python
    - pymatgen >=2022.3.7
    - python >=3.8
    - requests >=2.23.0
    - setuptools
    - typing-extensions >=3.7.4.1

test:
  imports:
    - mp_api.client
    - mp_api.client.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Server for the Materials Project
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
