{% set name = "mp-api" %}
{% set version = "0.40.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-api-{{ version }}.tar.gz
  sha256: 910f5e5f0ae2255f63ec803fa3e90d20f05e1f58e7f3a5b864db9ac75e424fba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - setuptools
    - msgpack-python
    - maggma >=0.57.1
    - pymatgen >=2022.3.7,<2024.2.20
    - typing-extensions >=3.7.4.1
    - requests >=2.23.0
    - monty >=2023.9.25
    - emmet-core >=0.78.0rc3

test:
  imports:
    - mp_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
