{% set name = "mp-api" %}
{% set version = "0.27.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-api-{{ version }}.tar.gz
  sha256: 17cc8139b393f1b258f12e395e3724e815b4fad30e67f7267d2e5c943b5491ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - emmet-core >=0.35.3
    - monty >=2021.3.12
    - msgpack-python
    - pymatgen >=2022.3.7
    - python >=3.8
    - requests >=2.23.0
    - setuptools
    - typing-extensions >=3.7.4.1

test:
  imports:
    - mp_api.client
    - mp_api.client.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Server for the Materials Project
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
