{% set name = "mp-api" %}
{% set version = "0.45.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7dda8328a806057ff94bcc0ae9426cd6cbe582919fa8a452ce51440435ad2f34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - smart_open
    - typing_extensions >=3.7.4.1
    - smart-open
    - python >={{ python_min }}
    - setuptools
    - msgpack-python
    - maggma >=0.57.1
    - pymatgen >=2022.3.7,!=2024.2.20
    - typing-extensions >=3.7.4.1
    - requests >=2.23.0
    - monty >=2024.12.10
    - emmet-core >=0.84.6rc0,<0.85

test:
  imports:
    - mp_api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/api
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
