{% set name = "mp-api" %}
{% set version = "0.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-api-{{ version }}.tar.gz
  sha256: cc4cde6f7adba24ee8ad662c94ec0fe5396e1924b4d1b2bd95847ff38d223962

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - setuptools
    - msgpack-python
    - maggma >=0.57.1
    - pymatgen >=2022.3.7
    - typing-extensions >=3.7.4.1
    - requests >=2.23.0
    - monty >=2023.9.25
    - emmet-core >=0.78.0

test:
  imports:
    - mp_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
