{% set name = "mp-api" %}
{% set version = "0.40.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-api-{{ version }}.tar.gz
  sha256: 771a70395ea4f1e06d08d92e830496a83001b102786afac2798b2169cf3c5509

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - setuptools
    - msgpack-python
    - maggma >=0.57.1
    - pymatgen >=2022.3.7,!=2024.2.20
    - typing-extensions >=3.7.4.1
    - requests >=2.23.0
    - monty >=2023.9.25
    - emmet-core >=0.78.0rc3

test:
  imports:
    - mp_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
