{% set name = "mp-api" %}
{% set version = "0.42.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 186fd738d82ecd7a442384376b883c8dbd81bd2c4809f3a4ea41a6001dc18cfe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - smart-open
    - python >=3.9
    - setuptools
    - msgpack-python
    - maggma >=0.57.1
    - pymatgen >=2022.3.7,!=2024.2.20
    - typing-extensions >=3.7.4.1
    - requests >=2.23.0
    - monty >=2023.9.25
    - emmet-core >=0.78.0rc3

test:
  imports:
    - mp_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/api
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
