schema_version: 1

context:
  name: mp-api
  version: "0.46.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 045588cfdcd1c3b68a3611b971e29a8f5be05d0cfd6776db702dc67fb90cf2c1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.11.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - orjson >=3.10,<4
    - boto3
    - smart_open
    - typing_extensions >=3.7.4.1
    - smart-open
    - python >=${{ python_min }}
    - setuptools
    - msgpack-python
    - maggma >=0.57.1
    - pymatgen >=2022.3.7,!=2024.2.20
    - typing-extensions >=3.7.4.1
    - requests >=2.23.0
    - monty >=2024.12.10
    - emmet-core >=0.86.3

tests:
  - python:
      imports:
        - mp_api
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/materialsproject/api

extra:
  recipe-maintainers:
    - jan-janssen
