schema_version: 1

context:
  name: mp-api
  version: "0.46.3"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 23fd367de99879cac4bf8d6ef1dff87c371a10aa7e6aea8bf97d8bf69e12d6db

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - orjson >=3.10,<4
    - boto3
    - typing_extensions >=3.7.4.1
    - python >=${{ python_min }}
    - pymatgen >2024.2.20
    - requests >=2.23.0
    - monty >=2024.12.10
    - emmet-core >=0.87.0,<0.87.2
    - deltalake >=1.4.0,<1.6.0
    - pyarrow >=20.0.0
tests:
  - python:
      imports:
        - mp_api
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: API Client for the Materials Project
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/materialsproject/api

extra:
  recipe-maintainers:
    - jan-janssen
